spring:
  application:
    name: central-server
  profiles:
    default: local

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
