DELETE FROM payment;
DELETE FROM reservation;
DELETE FROM seat;
DELETE FROM schedule;
DELETE FROM performance;

ALTER TABLE payment AUTO_INCREMENT = 1;
ALTER TABLE reservation AUTO_INCREMENT = 1;
ALTER TABLE seat AUTO_INCREMENT = 1;
ALTER TABLE schedule AUTO_INCREMENT = 1;
ALTER TABLE performance AUTO_INCREMENT = 1;
